openapi: 3.0.3
info:
  description: This is a library API
  version: 1.0.0
  title: Library
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: books client v7
    description: Search for books

paths:
  /external/v7/search:
    get:
      tags:
        - books client v7
      summary: Search for a book
      operationId: getAllV7
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                type: array,
                items:
                  $ref: "#/components/schemas/BookInfoV7"
        "400":
          description: Bad Request

components:
  schemas:
    BookInfoV7:
      title: External book Info
      description: Object containg all the info about a book
      type: object
      properties:
        name: {type: string}
        author: {type: string, minLength: 3}
        isbn: {type: string, pattern: "[0-9]{13}"}
      required: ["name", "author"]
